jimmer:
  language: kotlin
  show-sql: true
  pretty-sql: true
  inline-sql-variables: true
  database-validation-mode: warning
  dialect: org.babyfish.jimmer.sql.dialect.MySqlDialect

spring:
  data:
    redis:
      host: localhost
      port: 6379
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  servlet:
    multipart:
      max-request-size: 10GB
      max-file-size: 10GB
  datasource:
    url: jdbc:mysql://localhost/matchmaker?useUnicode=true&characterEncoding=utf8&useSSL=true&autoReconnect=true&reWriteBatchedInserts=true
    username: root
    password: 1234
  freemarker:
    suffix: .ftlh
    cache: false
sa-token:
  # token ??????? cookie ???
  token-name: auth
  # token ????????? ??30??-1 ??????
  timeout: -1
  # token ??????????????? token ???????????????????-1 ??????????
  active-timeout: 172800
  # ?????????????? ?? true ???????, ? false ??????????
  is-concurrent: false
  # ????????????????? token ?? true ????????? token, ? false ????????? token?
  is-share: false
  # token ?????????uuid?simple-uuid?random-32?random-64?random-128?tik?
  token-style: tik
  # ????????
  is-log: true
  is-read-cookie: false
  is-read-body: true
  is-read-header: true
server:
  port: 12346

uploadPath: ${user.dir}/upload/
domain: http://localhost:12346/
